POST http://localhost:3000/register/

Content-type:"Application/json"

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###



POST http://localhost:3000/login/

Content-type:"Application/json"

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###

GET http://localhost:3000/user/tweets/feed/

###

GET http://localhost:3000/tweets/3/

###

